### ISSUE TITLE
Post 0.1.0 release tasks

### ISSUE THREAD

**Issue by LaylBongers** [carbidegames/scheming-sun#6]
- [ ] Run a stress test with at least 32 concurrent players, with profiling enabled.

If performance and stability is good enough:
- [ ] A plan for 0.2.0 should be created.

If performance or stability isn't good enough:
- [ ] A plan for 0.1.1 should be made and another test should be run.
